import javax.swing.*;
import javax.xml.transform.Result;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.sql.*;
import java.util.Arrays;
import java.util.Collections;

/*Sections
Allows you to add / remove sections and edit their data.
Display
ID (Generated by SQL, not Editable)
Course (dropdown, based on active courses)
Teacher (dropdown, based on active teachers)
Roster
(Shown in a table that displays the student first name, last name and IDs)
Sorted by last name
Must be able to add and remove students to the section
Notes:

Deleting a teacher will set his/her sections to -1 (No Teacher Assigned)
Deleting a course will delete all corresponding sections of the course and update the teachers / students in those section to no longer have those sections.
Deleting a section will update the teachers / students in those section to no longer have those sections.*/

public class sectionsPanel extends JPanel{
    ArrayList<coursesData> allMyCourses = new ArrayList<>();
    JList<coursesData> myCourses = new JList<>();
    JScrollPane scrolling = new JScrollPane();

    JButton save = new JButton("Save");
    JButton clear = new JButton("Clear");
    JButton saveSectionChanges = new JButton("Save Changes");
    JButton deleteSection = new JButton("Delete Section");


    JButton saveStudent = new JButton("Save Student");
    JButton deleteStudent = new JButton("Delete Student");

    JButton saveChanges = new JButton("Save changes");
    JButton deleteContact = new JButton("Delete contact");

    ArrayList<sectionData> allMySections = new ArrayList<>();
    JList<sectionData> mySections = new JList<>();
    JScrollPane scrollingTwo = new JScrollPane();

    ArrayList<Data> allMyStudents = new ArrayList<>();
    JList<Data> myStudents = new JList<>();
    JScrollPane scrollingThree = new JScrollPane();

    JLabel ID = new JLabel("ID");
    JTextField IDText = new JTextField("");

    JLabel course = new JLabel("Course ID:");
    JTextField courseText = new JTextField();

    JLabel teacher = new JLabel("Teacher ID:");
    JTextField teacherText = new JTextField("");

    JLabel fnLabel = new JLabel("First Name");
    JLabel lnLabel = new JLabel("Last Name");
    JLabel studentIDLabel = new JLabel("ID");

    JTextField fn = new JTextField("");
    JTextField ln = new JTextField("");
    JTextField studentID = new JTextField("");

    JLabel sectionLabel = new JLabel("Sections");
    JLabel courseLabel = new JLabel("Courses");
    JLabel studentLabel = new JLabel("Students");
}
